<?php
/******************************************
 * US English
 * Admin Category Language
 ******************************************/

$lang['categories'] = 'Danh mục'; //'Categories';
$lang['error_must_select'] = 'Bạn phải chọn danh mục để tổ chức'; //'You must select a category to organize';
$lang['error_not_found'] = 'Không tìm thấy danh mục yêu cầu.'; //'The requested category could not be found.';
$lang['organize_category'] = 'Tổ chức "%s" Loại'; //'Organize "%s" Category';
$lang['organize'] = 'Tổ chức'; //'Organize';
$lang['category_id'] = 'ID'; //'ID';
$lang['category_form'] = 'Biểu mẫu loại'; //'Category Form';
$lang['name'] = 'Tên'; //'Name';
$lang['slug'] = 'Slug';
$lang['description'] = 'Mô tả'; //'Description';
$lang['excerpt'] = 'Trích dẫn'; //'Excerpt';
$lang['sequence'] = 'Dãy'; //'Sequence';
$lang['image'] = 'Hình ảnh'; //'Image';
$lang['seo_title'] = 'Tiêu đề SEO'; //'SEO Title';
$lang['meta'] = 'Meta Data'; //'Meta Data';
$lang['message_category_saved'] = 'Danh mục đã được lưu!'; //'The category has been saved!';
$lang['error_file_upload'] = '<p>Bạn chưa chọn tập tin nào để tải lên.</p>'; //'<p>You did not select a file to upload.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category'] = 'Danh mục đã được xóa.'; //'The category has been deleted.';
$lang['current_file'] = 'Tập tin hiện tại'; //'Current File';
$lang['confirm_delete_category'] = 'Bạn có chắc là mình muốn xóa danh mục này?'; //'Are you sure you want to delete this category?';
$lang['add_new_category'] = 'Tạo danh mục mới'; //'Add New Category';
$lang['top_level_category'] = 'Danh mục xếp hạng cao'; //'Top Level Category';
$lang['no_categories'] = 'Hiện tại không có danh mục nào cả'; //'There are currently no categories';
$lang['attributes'] = 'Thuộc tính'; //'Attributes';
$lang['seo'] = 'SEO'; //'SEO';
$lang['parent'] = 'Parent';
$lang['meta_data_description'] = 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;'; //'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop'] = 'Kéo và thả các sản phẩm theo trật tự bạn mong muốn.'; //'Drag and drop the products in the order you would like them to appear.';
$lang['sku'] = 'SKU';
$lang['price'] = 'Giá'; //'Price';
$lang['sale'] = 'Giảm giá'; //'Sale';
$lang['max_file_size'] = 'Dung lượng tập tin tối đa'; //'Max File Size';
$lang['pic'] = 'Người quản lý'; //'Person In Charge';